site_name: Knowledge Base Doumentation 

nav:
  - Home: Home.md
  - Fossid: Fossid.md
  - Publish-a-File: Publish-a-File.md
  - Inegration :
      - ROS: ROS.md
      - Sonarqube: Sonarqube.md
      
site_author: Mohammed Abdullah
site_description: >-
  Knowledge Base Article

# Repository
# repo_name: james-willett/material-mkdocs-tutorial
# repo_url: https://github.com/james-willett/material-mkdocs-tutorial

# Configuration
theme:
  custom_dir: custom_template
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.instant
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: purple
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/mhd8a"  target="_blank" rel="noopener"> Mohammed</a>
